### ISSUE TITLE
need this project

### ISSUE THREAD

**Issue by anurag-922** [theVatsal3802/attendance-management-system-student#1]
hi how can i used this for my college project

**Comment by theVatsal3802** [comment]
You can clone it and add your firebase setup instead of mine and it will work.

Also don't forget to setup your firebase project in firebase console.

**Comment by anurag-922** [comment]
Hi vatsal can you help me to establish the whole project with firebase setup.
Really want your help
To reach me here is my mail sharma922anurag@gmail.com

**Comment by theVatsal3802** [comment]
Yeah sure, I'll contact you as soon as I am free today.
