### ISSUE TITLE
Database Query

### ISSUE THREAD

**Issue by Vaishnavi8507** [theVatsal3802/attendance-management-system-student#2]

**Comment by theVatsal3802** [comment]
Hey @Vaishnavi8507, I am kind of busy with some work. Is it fine for if I help you in next week after Tuesday.

**Comment by Vaishnavi8507** [comment]
Thank you for your response.
Yeah sure when you will make time please let me know..

**Comment by theVatsal3802** [comment]
Yeah Sure, I'll let you know when I am free.

**Comment by Vaishnavi8507** [comment]
Hey sorry to bother you again.
If u are free can you please help me ..

**Comment by theVatsal3802** [comment]
Hey, sorry, I had totally forgot about the same.
Let me know when you will be able to join Google Meet so that we can resolve the issue.

**Comment by Vaishnavi8507** [comment]
Yeah sure if you are free then  can we start by 9:30.?

**Comment by theVatsal3802** [comment]
Yeah sure,
Please join the following link at 9:30
